app/admin/promo/models.py
from sqlalchemy import Column, Integer, String, Float, TIMESTAMP, select
from .database import Base, session
from datetime import datetime


# class Outlet(Base):
#     __tablename__ = 'azs'
#
#     id = Column(Integer, primary_key=True)
#     name = Column(String(50))
#     num = Column(Integer)
#     lat = Column(Float)
#     lon = Column(Float)
#     ip = Column(String(20))
#     token = Column(String(50))
#     status = Column(Integer)
#     ts_create = Column(TIMESTAMP, default=datetime.now())
#     ts_update = Column(TIMESTAMP, default=datetime.now())
#
#     @classmethod
#     def select(cls):
#         return select(cls)
#
#     @classmethod
#     def all(cls):
#         return cls.select().all()

app/data/views.py
from flask import Blueprint, jsonify, request
from app.auth import decorators, Auth
from app.promo.models import Product, Outlet, OutletProduct, OutletRequest, db
from sqlalchemy import and_, func
from app.manage.models import GroupAdvertise, Advertise
from app.auth.models import User
from datetime import datetime, timedelta
from src import formats
from .chart import Chart

data_app = Blueprint(
    'data',
    __name__
)


def render_json(result=True, data=None, status=200):
    return jsonify({
        'Result': result,
        'Data': data
    }), status


@data_app.route('/')
@decorators.login_required
def index():
    print(Auth.get_user())
    return 'data index'


def time_delta(var):
    res = timedelta(days=0)
    if var == '7d':
        res = timedelta(days=6)
    if var == '30d':
        res = timedelta(days=29)
    return res


def time_delta_period(date1: str, date2: str):
    d1 = datetime.strptime(date1, formats.DATE_JS)
    d2 = datetime.strptime(date2, formats.DATE_JS)
    day_list = []
    while d1 <= d2:
        day_list.append(d1)
        d1 = d1 + timedelta(days=1)
    return day_list


@data_app.route('/chart_product_created')
@decorators.login_required
def product_created():
    user = Auth.get_user()

    date1 = request.args.get('date1')
    date2 = request.args.get('date2')
    diapason = time_delta_period(date1, date2)
    labels = list(d.strftime(formats.DATE) for d in diapason)

    data = {
        'labels': labels,
        'datasets': []
    }
    products = user.products
    for (product, i) in zip(products, range(len(products))):
        product_period = {
            'label': product.name,
            'data': [],
            'index': i
        }
        for date in diapason:
            row = Product.get_create_product(product_id=product.id, date=date).all()
            product_period['data'].append(row[0][2] if len(row) else 0)
        data['datasets'].append(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': data
    })


@data_app.route('/chart_product_versus')
@decorators.login_required
def product_versus():
    user = Auth.get_user()

    chart = Chart()
    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    products = user.products
    labels = list(product.name for product in products)

    products_data = list(
        product.in_the_period(chart.args.date1, chart.args.date2).count()
        for product in products
    )

    chart.labels = labels
    chart.add_data({
            'data': products_data,
            'index': list(range(len(products)))
        })

    data = chart.get_data()

    return render_json(True, {
        'type': 'pie',
        'data': data
    })


@data_app.route('/chart_product_by_status/<product_id>')
@decorators.login_required
def product_by_status(product_id):
    user = Auth.get_user()

    chart = Chart()
    diapason = time_delta_period(chart.args.date1, chart.args.date2)
    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    product = Product.query.filter_by(id=product_id, user_id=user.id).first()
    func = [
        {
            'action': lambda x: Product.get_create_product(product_id=product.id, date=x). \
                filter(OutletProduct.ts_usage == None).all(),
            'title': 'Показан QR-код'
        }, {
            'action': lambda x: Product.get_usage_product(product_id=product.id, date=x).all(),
            'title': 'Показан подарок'
        }
    ]

    for f, i in zip(func, range(len(func))):
        product_period = {
            'label': f['title'],
            'data': [],
            'index': i
        }

        for date in diapason:
            row = f['action'](date)

            product_period['data'].append(row[0][2] if len(row) else 0)
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': chart.get_data()
    })


@data_app.route('/product_by_status_all_period/<product_id>')
@decorators.login_required
def product_by_status_all_period(product_id):
    user = Auth.get_user()

    chart = Chart()
    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    product = Product.query.filter_by(id=product_id, user_id=user.id).first()
    func = [
        {
            'action': lambda x: Product.get_create_product(product_id=product.id, date=x). \
                filter(OutletProduct.ts_usage == None).all(),
            'title': 'Показан QR-код'
        }, {
            'action': lambda x: Product.get_usage_product(product_id=product.id, date=x).all(),
            'title': 'Показан подарок'
        }
    ]
    chart.labels = list(f['title'] for f in func)
    product_period = {
        'label': chart.labels,
        'data': [],
        'index': list(range(len(func)))
    }

    for f, i in zip(func, range(len(func))):

        sum = 0
        for date in diapason:
            row = f['action'](date)
            sum += row[0][2] if len(row) else 0

        product_period['data'].append(sum)
    chart.add_data(product_period)

    return render_json(True, {
        'type': 'pie',
        'data': chart.get_data()
    })


@data_app.route('/advertise_clip_views_by_groups/')
@decorators.login_required
def advertise_clip_views_by_groups():
    user = Auth.get_user()

    date1 = request.args.get('date1')
    date2 = request.args.get('date2')
    diapason = time_delta_period(date1, date2)

    labels = list(d.strftime(formats.DATE) for d in diapason)

    data = {
        'labels': labels,
        'datasets': []
    }
    groups = GroupAdvertise.get_group_list(filters=[GroupAdvertise.Filters.actual]).filter_by(user_id=user.id)

    for group, i in zip(groups, range(groups.count())):
        product_period = {
            'label': group.title,
            'data': [],
            'index': i
        }

        for date in diapason:
            row = group.get_count_shows_per_day(day=date)

            product_period['data'].append(row)
        data['datasets'].append(product_period)

    return render_json(True, {
        'type': 'line',
        'data': data
    })


@data_app.route('/advertise_clip_views/<group_id>')
@decorators.login_required
def advertise_clip_views(group_id):
    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    advertise_list = Advertise.get_ads_list_by_group(group_id, [Advertise.Filters.actual])

    for ads, i in zip(advertise_list, range(advertise_list.count())):
        product_period = {
            'label': ads.title,
            'data': [],
            'index': i
        }

        for date in diapason:
            row = ads.get_count_shows_per_day(day=date).all()

            product_period['data'].append(len(row))
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'line',
        'data': chart.get_data()
    })


@data_app.route('/outlet_promo_qr_views')
@decorators.login_required
def outlet_promo_qr_views():
    user = Auth.get_user()

    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    outlet_items = Outlet.query.filter_by(user_id=user.id)

    for outlet, i in zip(outlet_items, range(outlet_items.count())):
        product_period = {
            'label': outlet.name,
            'data': [],
            'index': i
        }

        for date in diapason:
            row = outlet.get_create_product(outlet_id=outlet.id, date=date).first()

            product_period['data'].append(row[1] if row else 0)
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': chart.get_data()
    })


@data_app.route('/outlet_promo_qr_views_by_outlet/<outlet_id>')
@decorators.login_required
def outlet_promo_qr_views_by_outlet(outlet_id):
    user = Auth.get_user()

    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    outlet = Outlet.query.filter_by(id=outlet_id, user_id=user.id).first()

    func = [
        {
            'action': lambda x: outlet.get_create_product(outlet_id=outlet.id, date=x). \
                filter(OutletProduct.ts_usage == None).first(),
            'label': 'Показ QR-кода (без подарка)'
        },
        {
            'action': lambda x: outlet.get_usage_product(outlet_id=outlet.id, date=x).first(),
            'label': 'Показ подарка'
        }
    ]

    for f, i in zip(func, range(len(func))):
        product_period = {
            'label': f['label'],
            'data': [],
            'index': i
        }

        for date in diapason:
            row = f['action'](date)

            product_period['data'].append(row[1] if row else 0)
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': chart.get_data()
    })


@data_app.route('/outlet_promo_qr_views_by_outlet_all/<outlet_id>')
@decorators.login_required
def outlet_promo_qr_views_by_outlet_all(outlet_id):
    user = Auth.get_user()

    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    outlet = Outlet.query.filter_by(id=outlet_id, user_id=user.id).first()

    func = [
        {
            'action': lambda x: outlet.get_create_product(outlet_id=outlet.id, date=x). \
                filter(OutletProduct.ts_usage == None).first(),
            'label': 'Показ QR-кода (без перехода к показу подарка)'
        },
        {
            'action': lambda x: outlet.get_usage_product(outlet_id=outlet.id, date=x).first(),
            'label': 'Показ подарка'
        }
    ]
    chart.labels = list(f['label'] for f in func)
    product_period = {
        'label': chart.labels,

app/promo/__init__.py
from .views import promo_app

app/promo/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort, make_response
from sqlalchemy import or_, and_
from .models import *
from . import forms
from app.auth import decorators
from app.auth.auth import Auth
from src import exceptions

promo_app = Blueprint(
    'promo',
    __name__,
    template_folder='templates'
)

__all__ = ['promo_app']


@promo_app.route('/')
def index():
    # print(Product.get_showes_poduct(product_id=2).all())
    # session.rollback()

    return redirect(url_for('.outlet_list'))
    # return render_template('promo/index.html')


@promo_app.route('/outlets', methods=['GET'])
@decorators.login_required
def outlet_list():
    try:
        user = Auth.get_user()
        outlet_items = Outlet.query.filter_by(user_id=user.id)

        return render_template('promo/outlet/list.html', outlet_items=outlet_items)
    except Exception as err:
        return str(err)


@promo_app.route('/outletList/create', methods=['GET', 'POST'])
@decorators.login_required
def outlet_new():
    try:
        form = forms.NewOutlet()

        name = request.form.get('name')
        ip = request.form.get('ip')
        lat = request.form.get('lat')
        lon = request.form.get('lon')
        user = Auth.get_user()
        if form.new(name=name, lat=lat, lon=lon, ip=ip, user=user):
            flash(f'Точка добавлена')
            return redirect(url_for('promo.outlet_list'))

        return render_template('promo/outlet/new.html', form=form)
    except Exception as err:
        return str(err)


@promo_app.route('/outletList/<outlet_id>', methods=['GET', 'POST'])
@decorators.login_required
def outlet_edit(outlet_id):
    try:
        user = Auth.get_user()
        outlet = Outlet.query.filter_by(id=outlet_id, user_id=user.id).first()
        ads_groups = GroupAdvertise.get_group_list(filters=[GroupAdvertise.Filters.actual]).filter_by(user_id=user.id)

        if not outlet:
            raise exceptions.NotFoundPage()

        form_name = request.form.get('form_name')

        formOutlet = forms.NewOutlet()
        if formOutlet.is_form(form_name):
            name = request.form.get('name')
            ip = request.form.get('ip')
            lat = request.form.get('lat')
            lon = request.form.get('lon')
            status = request.form.get('status')
            if formOutlet.update(outlet=outlet, name=name, lat=lat, lon=lon, ip=ip, status=status):
                return redirect(request.path)

        formOutletAdsGroup = forms.OutletAdsGroup()
        choices = list(
            (group.id, group.title, 'selected' if outlet in group.outlets else '')
            for group in ads_groups)
        formOutletAdsGroup.set_ads_group_choices(choices)
        if formOutletAdsGroup.is_form(form_name):
            form_ads_groups = request.form.getlist('ads_groups')
            if formOutletAdsGroup.set(outlet, form_ads_groups):
                return redirect(request.path)

        formAdsGroupToken = forms.AdsGroupToken()
        if formAdsGroupToken.is_form(form_name):
            if formAdsGroupToken.token_create(outlet):
                return redirect(request.path)

        return render_template('promo/outlet/edit.html', formOutlet=formOutlet, outlet=outlet,
                               formOutletAdsGroup=formOutletAdsGroup, formAdsGroupToken=formAdsGroupToken)
    except exceptions.NotFoundPage:
        return render_template('404.html'), 404
    except Exception as err:
        return str(err)


@promo_app.route('/outletList/<outlet_id>/delete', methods=['GET', 'POST'])
@decorators.login_required
def outlet_delete(outlet_id):
    try:
        outlet: Outlet = Outlet.query.get(outlet_id)
        if not outlet:
            raise exceptions.NotFoundPage()

        form = forms.FormYes()
        if form.is_submitted():
            outlet.remove()
            return redirect(url_for('promo.outlet_list'))

        return render_template('promo/outlet/delete.html', outlet=outlet, form=form)
    except exceptions.NotFoundPage:
        return render_template('404.html'), 404


@promo_app.route('/products', methods=['GET'])
@decorators.login_required
def product_list():
    try:
        user = Auth.get_user()
        products = user.products  # Product.query

        return render_template('promo/products/products.html', products=products)
    except Exception as err:
        return str(err)


@promo_app.route('/products/create', methods=['GET', 'POST'])
@decorators.login_required
def product_new():
    form = forms.NewProduct()
    if form.is_submitted():
        name = request.form.get('name')
        code = request.form.get('code')
        date_begin = request.form.get('date_begin')
        date_end = request.form.get('date_end')
        max_count = request.form.get('max_count')
        max_count_per_outlet = request.form.get('max_count_per_outlet')
        bar_code = request.form.get('bar_code')
        enabled = request.form.get('enabled')

    if form.validate_on_submit():
        Product.new(
            name=name,
            code=code,
            date_begin=date_begin,
            date_end=date_end,
            max_count=max_count,
            max_count_per_outlet=max_count_per_outlet,
            bar_code=bar_code,
            enabled=enabled,
            user=Auth.get_user()
        )
        flash('Добавлен', 'success')
        return redirect(url_for('.product_list'))

    return render_template('promo/products/new.html', form=form)


@promo_app.route('/products/<product_id>/edit', methods=['GET', 'POST'])
@decorators.login_required
def product_edit(product_id):
    product = Product.query.get(product_id)

    form = forms.NewProduct()
    if form.is_submitted():
        name = request.form.get('name')
        code = request.form.get('code')
        date_begin = request.form.get('date_begin')
        date_end = request.form.get('date_end')
        max_count = request.form.get('max_count')
        max_count_per_outlet = request.form.get('max_count_per_outlet')
        bar_code = request.form.get('bar_code')
        enabled = request.form.get('enabled')

    if form.validate_on_submit():
        product.update(
            name=name,
            code=code,
            date_begin=date_begin,
            date_end=date_end,
            max_count=max_count,
            max_count_per_outlet=max_count_per_outlet,
            bar_code=bar_code,
            enabled=enabled
        )
        flash('Сохранено', 'success')
        return redirect(request.path)

    return render_template('promo/products/edit.html', product=product, form=form)


@promo_app.route('/products/<product_id>/delete', methods=['GET', 'POST'])
@decorators.login_required
def product_delete(product_id):
    product = Product.query.get(product_id)

    form = forms.FormYes()
    if form.validate_on_submit():
        product.remove()
        return redirect(url_for('.product_list'))

    return render_template('promo/products/delete.html', product=product, form=form)

app/promo/templates/promo/products/delete.html
{% extends 'base.html' %}

{% block title %}Удалить{% endblock %}

{% block content %}
    {% with title='Удалить точку '+product.name+'?' %}
        {% include 'components/label_of_page.html' %}
    {% endwith %}
    {% with crumbs=[
        {'url': url_for('head.index'), 'title': 'Главная страница'},
        {'url': url_for('promo.product_list'), 'title': 'Продукты'},
        {'url': url_for('promo.product_edit', product_id=product.id), 'title': product.name},
        {'url': '', 'title': 'Удаление'}
    ] %}
        {% include 'components/breadcrumbs.html' %}
    {% endwith %}
    <a href="{{ url_for('promo.product_delete', product_id=product.id) }}" class="btn"></a>
    <form action="{{ url_for('promo.product_delete', product_id=product.id) }}" method="POST">
        {{ form.csrf_token }}
        {{ form.submit_yes(class_='btn btn-primary') }}
        <a href="{{ url_for('promo.product_edit', product_id=product.id) }}" class="btn btn-outline-danger">Отмена</a>
    </form>
{% endblock %}

app/promo/templates/promo/products/edit.html
{% extends 'base.html' %}

{% block title %}
    Добавить
{% endblock %}

{% block css %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>
{% endblock %}

{% block content %}
    {% with title='Продукт ' + product.name %}
        {% include 'components/label_of_page.html' %}
    {% endwith %}
    {% with crumbs=[
        {'url': url_for('head.index'), 'title': 'Главная страница'},
        {'url': url_for('promo.product_list'), 'title': 'Продукты'},
        {'url': '', 'title': product.name}
    ] %}
        {% include 'components/breadcrumbs.html' %}
    {% endwith %}
    {% set char_id1 = utils.generate_string(10) %}
    {% with chart_index=char_id1 %}
        {% include 'components/chart/chart.html' %}
    {% endwith %}
    <div class="mb-2">
        <a href="{{ url_for('promo.product_delete', product_id=product.id ) }}"
           class="btn btn-outline-danger">Удалить {{ product.name }}</a>
    </div>
    {% include 'components/flash_messages.html' %}
    <form method="POST" action="{{ url_for('promo.product_edit', product_id=product.id) }}" class="mb-5">
        {{ form.csrf_token }}
        <div class="row justify-content-md-center">
            <div class="col-md-12">
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.name.label(class_='form-label', for=form.name.name) }}
                    </div>
                    <div class="col-md-10">
                        {{ form.name(class_='form-control', value=product.name) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.code.label(class_='form-label', for=form.code.name) }}
                    </div>
                    <div class="col-md-2">
                        {{ form.code(class_='form-control', value=product.code) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.date_begin.label(class_='form-label', for=form.date_begin.name) }}
                    </div>
                    <div class="col-md-2">
                        {{ form.date_begin(class_='form-control', value=product.date_begin|datetime('%Y-%m-%dT%H:%M')) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.date_end.label(class_='form-label', for=form.date_end.name) }}
                    </div>
                    <div class="col-md-2">
                        {{ form.date_end(class_='form-control', value=product.date_end|datetime('%Y-%m-%dT%H:%M')) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.max_count.label(class_='form-label', for=form.max_count.name) }}
                    </div>
                    <div class="col-md-2">
                        {{ form.max_count(class_='form-control', value=product.max_count) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.max_count_per_outlet.label(class_='form-label', for=form.max_count_per_outlet.name) }}
                    </div>
                    <div class="col-md-2">
                        {{ form.max_count_per_outlet(class_='form-control', value=product.max_count_per_outlet) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.bar_code.label(class_='form-label', for=form.bar_code.name) }}
                    </div>
                    <div class="col-md-2">
                        {{ form.bar_code(class_='form-control', value=product.bar_code) }}
                    </div>
                </div>
                <div class="row g-3 align-items-center mb-2">
                    <div class="col-md-2">
                        {{ form.enabled.label(class_='form-label', for=form.enabled.name) }}
                    </div>
                    <div class="col-md-2">
                        <select name="{{ form.enabled.name }}" id="{{ form.enabled.name }}" class="form-control">
                            {% for opt in form.enabled.choices %}
                                <option value="{{ opt[0] }}"
                                        {% if opt[0] == product.enabled %}selected{% endif %}>{{ opt[1] }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="d-flex justify-content-end">
                    <input type="submit" class="btn btn-outline-primary justify-content-end" value="Сохранить">
                </div>
            </div>
        </div>
    </form>

    <script>
        $(document).ready(function () {
            setSelectContentChart_{{ char_id1 }}({
                period: {
                    title: "Показы подарка за период",
                    url: "{{ url_for('data.product_by_status', product_id=product.id) }}"
                },
                all: {
                    title: "Показы QR-кода за период",
                    url: "{{ url_for('data.product_by_status_all_period', product_id=product.id) }}"
                }
            });
            renderChart_{{ char_id1 }}();
        })

    </script>
{% endblock %}

app/promo/templates/promo/products/products.html
{% extends 'base.html' %}

{% block title %}
    Продукты
{% endblock %}

{% block css %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>
{% endblock %}

{% block content %}
    {% with title='Продукты' %}
        {% include 'components/label_of_page.html' %}
    {% endwith %}
    {% with crumbs=[
        {'url': url_for('head.index'), 'title': 'Главная страница'},
        {'url': '', 'title': 'Продукты'},
    ] %}
        {% include 'components/breadcrumbs.html' %}
    {% endwith %}

    {% set char_id1 = utils.generate_string(10) %}
    {% with chart_index=char_id1 %}
        {% include 'components/chart/chart.html' %}
    {% endwith %}
    <div class="d-flex">
        <a href="{{ url_for('promo.product_new') }}" class="btn btn-outline-primary">
            Добавить продукт
        </a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование</th>
            <th scope="col">Код</th>
            <th scope="col">Дата начала</th>
            <th scope="col">Дата окончания</th>
            <th scope="col">Всего</th>
            <th scope="col">Всего для точки</th>
            <th scope="col">Баркод</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>
                    <a href="{{ url_for('promo.product_edit', product_id=product.id) }}" class="link-secondary">
                        {{ product.name }}
                    </a>
                </td>
                <td>{{ product.code }}</td>
                <td>{{ product.date_begin|datetime('%d.%m.%Y %H:%M:%S') }}</td>
                <td>{{ product.date_end|datetime('%d.%m.%Y %H:%M:%S') }}</td>
                <td>{{ product.bar_code }}</td>
                <td>{{ product.max_count }}</td>
                <td>{{ product.max_count_per_outlet }}</td>
                <td>{% if product.enabled == 1 %}
                    <span class="text-success">Активен</span>
                {% else %}
                    <span class="text-danger">Отключен</span>
                {% endif %}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <script>
        $(document).ready(function () {
            setSelectContentChart_{{ char_id1 }}({
            period: {
                title: "Показы подарков за период (по дням)",
                url: "{{ url_for('data.product_created') }}"
            },
            vs: {
                title: "Показы подарков за период (общий)",
                url: "{{ url_for('data.product_versus') }}"
            }
        });
            renderChart_{{ char_id1 }}()
        })

    </script>
{% endblock %}