app/admin/promo/models.py
from sqlalchemy import Column, Integer, String, Float, TIMESTAMP, select
from .database import Base, session
from datetime import datetime


# class Outlet(Base):
#     __tablename__ = 'azs'
#
#     id = Column(Integer, primary_key=True)
#     name = Column(String(50))
#     num = Column(Integer)
#     lat = Column(Float)
#     lon = Column(Float)
#     ip = Column(String(20))
#     token = Column(String(50))
#     status = Column(Integer)
#     ts_create = Column(TIMESTAMP, default=datetime.now())
#     ts_update = Column(TIMESTAMP, default=datetime.now())
#
#     @classmethod
#     def select(cls):
#         return select(cls)
#
#     @classmethod
#     def all(cls):
#         return cls.select().all()

app/data/views.py
from flask import Blueprint, jsonify, request
from app.auth import decorators, Auth
from app.promo.models import Product, Outlet, OutletProduct, OutletRequest, db
from sqlalchemy import and_, func
from app.manage.models import GroupAdvertise, Advertise
from app.auth.models import User
from datetime import datetime, timedelta
from src import formats
from .chart import Chart

data_app = Blueprint(
    'data',
    __name__
)


def render_json(result=True, data=None, status=200):
    return jsonify({
        'Result': result,
        'Data': data
    }), status


@data_app.route('/')
@decorators.login_required
def index():
    print(Auth.get_user())
    return 'data index'


def time_delta(var):
    res = timedelta(days=0)
    if var == '7d':
        res = timedelta(days=6)
    if var == '30d':
        res = timedelta(days=29)
    return res


def time_delta_period(date1: str, date2: str):
    d1 = datetime.strptime(date1, formats.DATE_JS)
    d2 = datetime.strptime(date2, formats.DATE_JS)
    day_list = []
    while d1 <= d2:
        day_list.append(d1)
        d1 = d1 + timedelta(days=1)
    return day_list


@data_app.route('/chart_product_created')
@decorators.login_required
def product_created():
    user = Auth.get_user()

    date1 = request.args.get('date1')
    date2 = request.args.get('date2')
    diapason = time_delta_period(date1, date2)
    labels = list(d.strftime(formats.DATE) for d in diapason)

    data = {
        'labels': labels,
        'datasets': []
    }
    products = user.products
    for (product, i) in zip(products, range(len(products))):
        product_period = {
            'label': product.name,
            'data': [],
            'index': i
        }
        for date in diapason:
            row = Product.get_create_product(product_id=product.id, date=date).all()
            product_period['data'].append(row[0][2] if len(row) else 0)
        data['datasets'].append(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': data
    })


@data_app.route('/chart_product_versus')
@decorators.login_required
def product_versus():
    user = Auth.get_user()

    chart = Chart()
    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    products = user.products
    labels = list(product.name for product in products)

    products_data = list(
        product.in_the_period(chart.args.date1, chart.args.date2).count()
        for product in products
    )

    chart.labels = labels
    chart.add_data({
            'data': products_data,
            'index': list(range(len(products)))
        })

    data = chart.get_data()

    return render_json(True, {
        'type': 'pie',
        'data': data
    })


@data_app.route('/chart_product_by_status/<product_id>')
@decorators.login_required
def product_by_status(product_id):
    user = Auth.get_user()

    chart = Chart()
    diapason = time_delta_period(chart.args.date1, chart.args.date2)
    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    product = Product.query.filter_by(id=product_id, user_id=user.id).first()
    func = [
        {
            'action': lambda x: Product.get_create_product(product_id=product.id, date=x). \
                filter(OutletProduct.ts_usage == None).all(),
            'title': 'Показан QR-код'
        }, {
            'action': lambda x: Product.get_usage_product(product_id=product.id, date=x).all(),
            'title': 'Показан подарок'
        }
    ]

    for f, i in zip(func, range(len(func))):
        product_period = {
            'label': f['title'],
            'data': [],
            'index': i
        }

        for date in diapason:
            row = f['action'](date)

            product_period['data'].append(row[0][2] if len(row) else 0)
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': chart.get_data()
    })


@data_app.route('/product_by_status_all_period/<product_id>')
@decorators.login_required
def product_by_status_all_period(product_id):
    user = Auth.get_user()

    chart = Chart()
    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    product = Product.query.filter_by(id=product_id, user_id=user.id).first()
    func = [
        {
            'action': lambda x: Product.get_create_product(product_id=product.id, date=x). \
                filter(OutletProduct.ts_usage == None).all(),
            'title': 'Показан QR-код'
        }, {
            'action': lambda x: Product.get_usage_product(product_id=product.id, date=x).all(),
            'title': 'Показан подарок'
        }
    ]
    chart.labels = list(f['title'] for f in func)
    product_period = {
        'label': chart.labels,
        'data': [],
        'index': list(range(len(func)))
    }

    for f, i in zip(func, range(len(func))):

        sum = 0
        for date in diapason:
            row = f['action'](date)
            sum += row[0][2] if len(row) else 0

        product_period['data'].append(sum)
    chart.add_data(product_period)

    return render_json(True, {
        'type': 'pie',
        'data': chart.get_data()
    })


@data_app.route('/advertise_clip_views_by_groups/')
@decorators.login_required
def advertise_clip_views_by_groups():
    user = Auth.get_user()

    date1 = request.args.get('date1')
    date2 = request.args.get('date2')
    diapason = time_delta_period(date1, date2)

    labels = list(d.strftime(formats.DATE) for d in diapason)

    data = {
        'labels': labels,
        'datasets': []
    }
    groups = GroupAdvertise.get_group_list(filters=[GroupAdvertise.Filters.actual]).filter_by(user_id=user.id)

    for group, i in zip(groups, range(groups.count())):
        product_period = {
            'label': group.title,
            'data': [],
            'index': i
        }

        for date in diapason:
            row = group.get_count_shows_per_day(day=date)

            product_period['data'].append(row)
        data['datasets'].append(product_period)

    return render_json(True, {
        'type': 'line',
        'data': data
    })


@data_app.route('/advertise_clip_views/<group_id>')
@decorators.login_required
def advertise_clip_views(group_id):
    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    advertise_list = Advertise.get_ads_list_by_group(group_id, [Advertise.Filters.actual])

    for ads, i in zip(advertise_list, range(advertise_list.count())):
        product_period = {
            'label': ads.title,
            'data': [],
            'index': i
        }

        for date in diapason:
            row = ads.get_count_shows_per_day(day=date).all()

            product_period['data'].append(len(row))
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'line',
        'data': chart.get_data()
    })


@data_app.route('/outlet_promo_qr_views')
@decorators.login_required
def outlet_promo_qr_views():
    user = Auth.get_user()

    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    outlet_items = Outlet.query.filter_by(user_id=user.id)

    for outlet, i in zip(outlet_items, range(outlet_items.count())):
        product_period = {
            'label': outlet.name,
            'data': [],
            'index': i
        }

        for date in diapason:
            row = outlet.get_create_product(outlet_id=outlet.id, date=date).first()

            product_period['data'].append(row[1] if row else 0)
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': chart.get_data()
    })


@data_app.route('/outlet_promo_qr_views_by_outlet/<outlet_id>')
@decorators.login_required
def outlet_promo_qr_views_by_outlet(outlet_id):
    user = Auth.get_user()

    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    outlet = Outlet.query.filter_by(id=outlet_id, user_id=user.id).first()

    func = [
        {
            'action': lambda x: outlet.get_create_product(outlet_id=outlet.id, date=x). \
                filter(OutletProduct.ts_usage == None).first(),
            'label': 'Показ QR-кода (без подарка)'
        },
        {
            'action': lambda x: outlet.get_usage_product(outlet_id=outlet.id, date=x).first(),
            'label': 'Показ подарка'
        }
    ]

    for f, i in zip(func, range(len(func))):
        product_period = {
            'label': f['label'],
            'data': [],
            'index': i
        }

        for date in diapason:
            row = f['action'](date)

            product_period['data'].append(row[1] if row else 0)
        chart.add_data(product_period)

    return render_json(True, {
        'type': 'stackedBar',
        'data': chart.get_data()
    })


@data_app.route('/outlet_promo_qr_views_by_outlet_all/<outlet_id>')
@decorators.login_required
def outlet_promo_qr_views_by_outlet_all(outlet_id):
    user = Auth.get_user()

    chart = Chart()

    diapason = time_delta_period(chart.args.date1, chart.args.date2)

    chart.labels = list(d.strftime(formats.DATE) for d in diapason)

    outlet = Outlet.query.filter_by(id=outlet_id, user_id=user.id).first()

    func = [
        {
            'action': lambda x: outlet.get_create_product(outlet_id=outlet.id, date=x). \
                filter(OutletProduct.ts_usage == None).first(),
            'label': 'Показ QR-кода (без перехода к показу подарка)'
        },
        {
            'action': lambda x: outlet.get_usage_product(outlet_id=outlet.id, date=x).first(),
            'label': 'Показ подарка'
        }
    ]
    chart.labels = list(f['label'] for f in func)
    product_period = {
        'label': chart.labels,

app/promo/__init__.py
from .views import promo_app

app/promo/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort, make_response
from sqlalchemy import or_, and_
from .models import *
from . import forms
from app.auth import decorators
from app.auth.auth import Auth
from src import exceptions

promo_app = Blueprint(
    'promo',
    __name__,
    template_folder='templates'
)

__all__ = ['promo_app']


@promo_app.route('/')
def index():
    # print(Product.get_showes_poduct(product_id=2).all())
    # session.rollback()

    return redirect(url_for('.outlet_list'))
    # return render_template('promo/index.html')


@promo_app.route('/outlets', methods=['GET'])
@decorators.login_required
def outlet_list():
    try:
        user = Auth.get_user()
        outlet_items = Outlet.query.filter_by(user_id=user.id)

        return render_template('promo/outlet/list.html', outlet_items=outlet_items)
    except Exception as err:
        return str(err)


@promo_app.route('/outletList/create', methods=['GET', 'POST'])
@decorators.login_required
def outlet_new():
    try:
        form = forms.NewOutlet()

        name = request.form.get('name')
        ip = request.form.get('ip')
        lat = request.form.get('lat')
        lon = request.form.get('lon')
        user = Auth.get_user()
        if form.new(name=name, lat=lat, lon=lon, ip=ip, user=user):
            flash(f'Точка добавлена')
            return redirect(url_for('promo.outlet_list'))

        return render_template('promo/outlet/new.html', form=form)
    except Exception as err:
        return str(err)


@promo_app.route('/outletList/<outlet_id>', methods=['GET', 'POST'])
@decorators.login_required
def outlet_edit(outlet_id):
    try:
        user = Auth.get_user()
        outlet = Outlet.query.filter_by(id=outlet_id, user_id=user.id).first()
        ads_groups = GroupAdvertise.get_group_list(filters=[GroupAdvertise.Filters.actual]).filter_by(user_id=user.id)

        if not outlet:
            raise exceptions.NotFoundPage()

        form_name = request.form.get('form_name')

        formOutlet = forms.NewOutlet()
        if formOutlet.is_form(form_name):
            name = request.form.get('name')
            ip = request.form.get('ip')
            lat = request.form.get('lat')
            lon = request.form.get('lon')
            status = request.form.get('status')
            if formOutlet.update(outlet=outlet, name=name, lat=lat, lon=lon, ip=ip, status=status):
                return redirect(request.path)

        formOutletAdsGroup = forms.OutletAdsGroup()
        choices = list(
            (group.id, group.title, 'selected' if outlet in group.outlets else '')
            for group in ads_groups)
        formOutletAdsGroup.set_ads_group_choices(choices)
        if formOutletAdsGroup.is_form(form_name):
            form_ads_groups = request.form.getlist('ads_groups')
            if formOutletAdsGroup.set(outlet, form_ads_groups):
                return redirect(request.path)

        formAdsGroupToken = forms.AdsGroupToken()
        if formAdsGroupToken.is_form(form_name):
            if formAdsGroupToken.token_create(outlet):
                return redirect(request.path)

        return render_template('promo/outlet/edit.html', formOutlet=formOutlet, outlet=outlet,
                               formOutletAdsGroup=formOutletAdsGroup, formAdsGroupToken=formAdsGroupToken)
    except exceptions.NotFoundPage:
        return render_template('404.html'), 404
    except Exception as err:
        return str(err)


@promo_app.route('/outletList/<outlet_id>/delete', methods=['GET', 'POST'])
@decorators.login_required
def outlet_delete(outlet_id):
    try:
        outlet: Outlet = Outlet.query.get(outlet_id)
        if not outlet:
            raise exceptions.NotFoundPage()

        form = forms.FormYes()
        if form.is_submitted():
            outlet.remove()
            return redirect(url_for('promo.outlet_list'))

        return render_template('promo/outlet/delete.html', outlet=outlet, form=form)
    except exceptions.NotFoundPage:
        return render_template('404.html'), 404


@promo_app.route('/products', methods=['GET'])
@decorators.login_required
def product_list():
    try:
        user = Auth.get_user()
        products = user.products  # Product.query

        return render_template('promo/products/products.html', products=products)
    except Exception as err:
        return str(err)


@promo_app.route('/products/create', methods=['GET', 'POST'])
@decorators.login_required
def product_new():
    form = forms.NewProduct()
    if form.is_submitted():
        name = request.form.get('name')
        code = request.form.get('code')
        date_begin = request.form.get('date_begin')
        date_end = request.form.get('date_end')
        max_count = request.form.get('max_count')
        max_count_per_outlet = request.form.get('max_count_per_outlet')
        bar_code = request.form.get('bar_code')
        enabled = request.form.get('enabled')

    if form.validate_on_submit():
        Product.new(
            name=name,
            code=code,
            date_begin=date_begin,
            date_end=date_end,
            max_count=max_count,
            max_count_per_outlet=max_count_per_outlet,
            bar_code=bar_code,
            enabled=enabled,
            user=Auth.get_user()
        )
        flash('Добавлен', 'success')
        return redirect(url_for('.product_list'))

    return render_template('promo/products/new.html', form=form)


@promo_app.route('/products/<product_id>/edit', methods=['GET', 'POST'])
@decorators.login_required
def product_edit(product_id):
    product = Product.query.get(product_id)

    form = forms.NewProduct()
    if form.is_submitted():
        name = request.form.get('name')
        code = request.form.get('code')
        date_begin = request.form.get('date_begin')
        date_end = request.form.get('date_end')
        max_count = request.form.get('max_count')
        max_count_per_outlet = request.form.get('max_count_per_outlet')
        bar_code = request.form.get('bar_code')
        enabled = request.form.get('enabled')

    if form.validate_on_submit():
        product.update(
            name=name,
            code=code,
            date_begin=date_begin,
            date_end=date_end,
            max_count=max_count,
            max_count_per_outlet=max_count_per_outlet,
            bar_code=bar_code,
            enabled=enabled
        )
        flash('Сохранено', 'success')
        return redirect(request.path)

    return render_template('promo/products/edit.html', product=product, form=form)


@promo_app.route('/products/<product_id>/delete', methods=['GET', 'POST'])
@decorators.login_required
def product_delete(product_id):
    product = Product.query.get(product_id)

    form = forms.FormYes()
    if form.validate_on_submit():
        product.remove()
        return redirect(url_for('.product_list'))

    return render_template('promo/products/delete.html', product=product, form=form)

app/promo/templates/promo/outlet/delete.html
{% extends 'base.html' %}

{% block title %}Удалить{% endblock %}

{% block content %}
    {% with title='Удалить точку '+outlet.name+'?' %}
        {% include 'components/label_of_page.html' %}
    {% endwith %}
    {% with crumbs=[
        {'url': url_for('head.index'), 'title': 'Главная страница'},
        {'url': url_for('promo.outlet_list'), 'title': 'Торговые точки'},
        {'url': url_for('promo.outlet_edit', outlet_id=outlet.id), 'title': 'Точка ' + outlet.name},
        {'url': '', 'title': 'Удаление'}
    ] %}
        {% include 'components/breadcrumbs.html' %}
    {% endwith %}
    <a href="{{ url_for('promo.outlet_delete', outlet_id=outlet.id) }}" class="btn"></a>
    <form action="{{ url_for('promo.outlet_delete', outlet_id=outlet.id) }}" method="POST">
        {{ form.csrf_token }}
        {{ form.submit_yes(class_='btn btn-primary') }}
        <a href="{{ url_for('promo.outlet_edit', outlet_id=outlet.id) }}" class="btn btn-outline-danger">Отмена</a>
    </form>
{% endblock %}

app/promo/templates/promo/outlet/edit.html
{% extends 'base.html' %}

{% block title %}
    Добавить
{% endblock %}

{% block css %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>
{% endblock %}

{% block content %}
    {% with title='Точка ' + outlet.name %}
        {% include 'components/label_of_page.html' %}
    {% endwith %}
    {% with crumbs=[
        {'url': url_for('head.index'), 'title': 'Главная страница'},
        {'url': url_for('promo.index'), 'title': 'Торговые точки'},
        {'url': '', 'title': 'Точка ' + outlet.name}
    ] %}
        {% include 'components/breadcrumbs.html' %}
    {% endwith %}
    {% with chart_index=char_id1 %}
        {% include 'components/chart/chart.html' %}
    {% endwith %}
    <div class="mb-2">
        <a href="{{ url_for('promo.outlet_delete', outlet_id=outlet.id ) }}"
           class="btn btn-outline-danger">Удалить {{ outlet.name }}</a>
    </div>
    {{ tab }}
    <ul class="nav nav-tabs mb-4" id="outletTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="setting-tab" data-bs-toggle="tab" data-bs-target="#setting"
                    type="button" onclick="setTabOutlet('setting')"
                    role="tab" aria-controls="setting" aria-selected="true"> Настройки
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="advertise-tab" data-bs-toggle="tab" data-bs-target="#advertise"
                    type="button" onclick="setTabOutlet('advertise')"
                    role="tab" aria-controls="advertise" aria-selected="false">Реклама
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="auth_token-tab" data-bs-toggle="tab" data-bs-target="#auth_token"
                    type="button" onclick="setTabOutlet('auth_token')"
                    role="tab" aria-controls="auth_token" aria-selected="false">Доступ
            </button>
        </li>
    </ul>
    {{ request.hash }}
    {% include 'components/flash_messages.html' %}

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="setting" role="tabpanel" aria-labelledby="setting-tab">
            <form method="POST" action="{{ url_for('promo.outlet_edit', outlet_id=outlet.id) }}">
                {{ formOutlet.csrf_token }}
                {{ formOutlet.form_name }}
                <div class="row justify-content-md-center">
                    <div class="col-md-12">
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formOutlet.name.label(class_='form-label', for=formOutlet.name.name) }}
                            </div>
                            <div class="col-md-10">
                                {{ formOutlet.name(class_='form-control', value=outlet.name) }}
                            </div>
                        </div>
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formOutlet.ip.label(class_='form-label', for=formOutlet.ip.name) }}
                            </div>
                            <div class="col-md-10">
                                {{ formOutlet.ip(class_='form-control', placeholder='192.168.1.1', value=outlet.ip) }}
                            </div>
                        </div>
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formOutlet.lat.label(class_='form-label', for=formOutlet.lat.name) }}
                            </div>
                            <div class="col-md-10">
                                {{ formOutlet.lat(class_='form-control', value=outlet.lat) }}
                            </div>
                        </div>
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formOutlet.lon.label(class_='form-label', for=formOutlet.lon.name) }}
                            </div>
                            <div class="col-md-10">
                                {{ formOutlet.lon(class_='form-control', value=outlet.lon) }}
                            </div>
                        </div>
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formOutlet.status.label(class_='form-label', for=formOutlet.status.name) }}
                            </div>
                            <div class="col-md-10">
                                <select name="{{ formOutlet.status.name }}" id="{{ formOutlet.status.name }}"
                                        class="form-control">
                                    {% for opt in formOutlet.status.choices %}
                                        <option value="{{ opt[0] }}"
                                                {% if opt[0] == outlet.status %}selected{% endif %}>{{ opt[1] }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="d-flex justify-content-end">
                            <input type="submit" class="btn btn-outline-primary justify-content-end" value="Сохранить">
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="tab-pane fade" id="advertise" role="tabpanel" aria-labelledby="advertise-tab">
            <form action="{{ url_for('.outlet_edit', outlet_id=outlet.id) }}" method="POST">
                {{ formOutletAdsGroup.csrf_token }}
                {{ formOutletAdsGroup.form_name }}

                <div class="row justify-content-md-center">
                    <div class="col-md-12">
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formOutletAdsGroup.ads_groups.label(class_='form-label', for=formOutletAdsGroup.ads_groups.name) }}
                            </div>
                            <div class="col-md-10">
                                <select id="{{ formOutletAdsGroup.ads_groups.name }}"
                                        name="{{ formOutletAdsGroup.ads_groups.name }}" multiple class="form-control">
                                    {% for group in formOutletAdsGroup.ads_groups.choices %}
                                        <option value="{{ group[0] }}" {{ group[2] }}>{{ group[1] }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        {% with errors=formOutletAdsGroup.ads_groups.errors %}
                            {% include 'components/forms/errors.html' %}
                        {% endwith %}
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <input type="submit" class="btn btn-outline-primary" value="Сохранить">
                </div>
            </form>
        </div>
        <div class="tab-pane fade" id="auth_token" role="tabpanel" aria-labelledby="advertise-tab">
            <form action="{{ url_for('.outlet_edit', outlet_id=outlet.id) }}" method="POST">
                {{ formAdsGroupToken.csrf_token }}
                {{ formAdsGroupToken.form_name }}

                <div class="row justify-content-md-center">
                    <div class="col-md-12">
                        <div class="row g-3 align-items-center mb-2">
                            <div class="col-md-2">
                                {{ formAdsGroupToken.token.label(class_='form-label', for=formAdsGroupToken.token.name) }}
                            </div>
                            <div class="col-md-10 d-flex">
                                {{ formAdsGroupToken.token(class_="form-control", style="margin-right: 5px",
                                    readonly=True, value=outlet.auth_token[0].token if outlet.auth_token else '') }}
                                <a class="btn btn-primary" onclick="copyToken()">Копировать</a>
                            </div>
                        </div>
                        {% with errors=formAdsGroupToken.token.errors %}
                            {% include 'components/forms/errors.html' %}
                        {% endwith %}
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <input type="submit" class="btn btn-outline-primary" value="Обновить">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script>
        const tabOutlet = localStorage.getItem('tabOutlet');
        const setTabOutlet = (tabName) => {
            localStorage.setItem('tabOutlet', tabName)
        };

        const turnTabOutlet = (tabName) => {
            const tabs = document.querySelector('#outletTab').querySelectorAll('li');

            let eventClick = new Event('click');
            for (let i = 0; i < tabs.length; i++) {
                const button = tabs[i].querySelector('button');
                if (button.dataset['bsTarget'].indexOf(tabName) > -1) {
                    button.dispatchEvent(eventClick);
                }
            }
        };

        $(document).ready(function () {
            turnTabOutlet(tabOutlet);
        });


        const copyToken = () => {
            const inputToken = document.getElementById("token");
            inputToken.select();
            document.execCommand("copy");
        }
    </script>
    <script>
        $(document).ready(function () {
            setSelectContentChart_{{ char_id1 }}({
                period: {
                    title: "Показы QR-кода за период (по дням)",
                    url: "{{ url_for('data.outlet_promo_qr_views_by_outlet', outlet_id=outlet.id) }}"
                },
                all: {
                    title: "Показы QR-кода за период (общий)",
                    url: "{{ url_for('data.outlet_promo_qr_views_by_outlet_all', outlet_id=outlet.id) }}"
                }
            });
            renderChart_{{ char_id1 }}()
        })

    </script>

{% endblock %}